; Conformance test for the (crab math) bundled Scheme extension —
; combinatorics + numeric helpers. (The Rust half — special functions
; and statistics — is covered by crab-math.scm.)

(test-section "(crab math) — combinatorics")
(test-equal "factorial 0" 1 (factorial 0))
(test-equal "factorial 5" 120 (factorial 5))
(test-equal "factorial promotes to bignum" 51090942171709440000 (factorial 21))
(test-equal "binomial n 0" 1 (binomial 7 0))
(test-equal "binomial n n" 1 (binomial 7 7))
(test-equal "binomial 5 2" 10 (binomial 5 2))
(test-equal "binomial 52 5" 2598960 (binomial 52 5))
(test-equal "binomial out of range" 0 (binomial 3 5))

(test-section "(crab math) — numeric helpers")
(test-equal "clamp below the range" 0 (clamp -3 0 10))
(test-equal "clamp above the range" 10 (clamp 99 0 10))
(test-equal "clamp inside the range" 5 (clamp 5 0 10))
(test-equal "sum of a list" 15 (sum '(1 2 3 4 5)))
(test-equal "sum of the empty list" 0 (sum '()))
(test-equal "product of a list" 120 (product '(1 2 3 4 5)))
(test-equal "product of the empty list" 1 (product '()))
(test-equal "sign of a negative" -1 (sign -7))
(test-equal "sign of zero" 0 (sign 0))
(test-equal "sign of a positive" 1 (sign 3))

(test-section "(crab math) — prime?")
(test-false "0 is not prime" (prime? 0))
(test-false "1 is not prime" (prime? 1))
(test-true "2 is prime" (prime? 2))
(test-true "7 is prime" (prime? 7))
(test-false "9 is not prime" (prime? 9))
(test-true "97 is prime" (prime? 97))
(test-false "100 is not prime" (prime? 100))
