#!/usr/bin/env bash
# AOT vs other-runtime perf comparison (hyperfine-based).
#
# This is the missing column in microbench/run.sh: it puts the AOT
# native-binary tier side-by-side with the walker / VM / JIT tiers,
# rustc -O, and the mature comparison Schemes (Chez / Guile / Gambit,
# plus Gambit's own AOT path), all on the SAME workload.
#
# Two regimes, because they answer different questions:
#
#   --regime canonical : each bench at the .scm file's own (small) N.
#       Wall time is startup-inclusive, so this is the "small program /
#       cold invocation" picture — where AOT's near-zero startup and the
#       JIT's per-run compile cost dominate over compute. Includes the
#       walker tier and rustc -O. (At these N, fib/tak/etc. compute is
#       sub-millisecond — see microbench/README.md's startup caveat.)
#
#   --regime heavy     : N scaled up per bench so compute dominates the
#       ~3 ms process-startup floor. This is the steady-state CODEGEN
#       comparison — AOT vs JIT (both cranelift), vs the VM, vs LLVM-
#       native rust, vs the production Schemes. The walker tier is
#       dropped (it is 30-40x the VM and would take minutes at heavy N).
#
#   --regime both (default) : run canonical then heavy.
#
# WHY a fresh harness and not an extension of aot-comparison.sh: that
# script's per-bench N drifted out of sync with the .scm files (it timed
# fib at 35 while the .scm — and every other tier in run.sh — used 25, a
# ~123x workload mismatch), and it used best-of-3 /usr/bin/time rather
# than hyperfine's warmup + statistics. This harness drives EVERY runtime
# at one shared N per bench and times with hyperfine.
#
# Runtimes (auto-detected on PATH; absent ones are silently skipped):
#   aot         crabscheme AOT native binary  (crabscheme aot --multi --build)
#   jit         crabscheme --tier vm-jit
#   vm          crabscheme --tier vm
#   walker      crabscheme --tier walker      (canonical regime only)
#   rust-O      rustc -O reference impl
#   chez        chez scheme  (`scheme --script`)
#   guile       guile -q
#   gambit      gsi (Gambit interpreter)
#   gambit-aot  gsc -dynamic .o1 loaded via gsi  (Gambit's AOT path)
#   (racket is intentionally excluded: it rejects a bare .scm with no #lang.)
#
# Outputs:
#   - per-bench hyperfine table to stdout (ranked, with relative speeds)
#   - JSON per bench under target/aot-vs-runtimes/results/<regime>/<bench>.json
#   - a combined markdown table at results/<regime>-table.md (also printed)

set -uo pipefail
cd "$(dirname "$0")" || exit 1
ROOT=$(cd .. && pwd)

CS="$ROOT/target/release/crabscheme"
SCM_DIR="$ROOT/bench/microbench/scheme"
RUST_DIR="$ROOT/bench/microbench/rust"
WORK="$ROOT/target/aot-vs-runtimes"
RUST_CANON_OUT="$ROOT/target/release-microbench"
RUST_HEAVY_OUT="$WORK/rust-heavy"

REGIME="both"
ONLY_BENCH=""
while [ $# -gt 0 ]; do
  case "$1" in
    --regime) REGIME="$2"; shift 2 ;;
    --bench)  ONLY_BENCH="$2"; shift 2 ;;
    *) echo "usage: $0 [--regime canonical|heavy|both] [--bench NAME]"; exit 2 ;;
  esac
done

command -v hyperfine >/dev/null 2>&1 || { echo "need hyperfine on PATH"; exit 1; }
command -v python3   >/dev/null 2>&1 || { echo "need python3 on PATH";   exit 1; }

# --- build crabscheme (release) once ---
if [ ! -x "$CS" ]; then
  echo "==> building crabscheme (release)..."
  (cd "$ROOT" && cargo build --release -p cs-cli --bin crabscheme >/dev/null 2>&1)
fi
[ -x "$CS" ] || { echo "missing $CS"; exit 1; }

BENCHES=(fib tak ack nqueens mandelbrot spectral-norm binary-trees alloc-stress)

# entry function name (the AOT --entry / --multi dispatch key)
declare -A ENTRY=(
  [fib]=fib [tak]=tak [ack]=ack [nqueens]=nqueens
  [mandelbrot]=mandelbrot [spectral-norm]=spectral-norm
  [binary-trees]=run [alloc-stress]=alloc-stress )

# canonical args == the workload baked into each .scm's own driver.
declare -A CANON=(
  [fib]="25" [tak]="18 12 6" [ack]="3 6" [nqueens]="8"
  [mandelbrot]="80" [spectral-norm]="50" [binary-trees]="10" [alloc-stress]="200" )

# heavy args: scaled so compute dominates the ~3 ms startup floor while
# keeping the VM tier in the ~0.5-2.5 s range (tuned empirically below).
declare -A HEAVY=(
  [fib]="35" [tak]="24 16 8" [ack]="3 9" [nqueens]="10"
  [mandelbrot]="280" [spectral-norm]="150" [binary-trees]="14" [alloc-stress]="8000" )

# The exact literal in each rust main() that carries N (so the heavy
# rust binary can be regenerated by a single str.replace + rustc -O).
declare -A RUST_OLD=(
  [fib]="let n = 25;" [tak]="tak(18, 12, 6)" [ack]="ack(3, 6)"
  [nqueens]="place(1, 8, &mut placed)" [mandelbrot]="let n = 80;"
  [spectral-norm]="let n = 50;" [binary-trees]="let depth = 10;"
  [alloc-stress]="let n = 200;" )
declare -A RUST_NEW=(
  [fib]="let n = 35;" [tak]="tak(24, 16, 8)" [ack]="ack(3, 9)"
  [nqueens]="place(1, 10, &mut placed)" [mandelbrot]="let n = 280;"
  [spectral-norm]="let n = 150;" [binary-trees]="let depth = 14;"
  [alloc-stress]="let n = 8000;" )

# str.replace via python — sidesteps sed escaping of (), &, ; in literals.
subst() { python3 -c 'import sys;open(sys.argv[2],"w").write(open(sys.argv[1]).read().replace(sys.argv[3],sys.argv[4]))' "$1" "$2" "$3" "$4"; }

# Generate a heavy-N .scm: keep every definition (everything before the
# first top-level "(display" driver line) and append our own driver that
# calls ENTRY at the heavy args. Uniform across all 8 benches.
gen_heavy_scm() {
  local bench="$1" out="$2"
  awk '/^\(display/{exit} {print}' "$SCM_DIR/$bench.scm" > "$out"
  printf '(display (%s %s))(newline)\n' "${ENTRY[$bench]}" "${HEAVY[$bench]}" >> "$out"
}

# last whitespace token of stdout — the bench's numeric answer, used as a
# cross-runtime correctness check (AOT prints "75025"; the file-runners
# print "fib(25) = 75025"; both reduce to "75025").
last_token() { awk 'END{print $NF}'; }

run_regime() {
  local regime="$1"
  local outdir="$WORK/results/$regime"
  mkdir -p "$outdir"
  echo
  echo "########################################################"
  echo "## regime: $regime"
  echo "########################################################"

  local hf_warmup hf_args
  if [ "$regime" = canonical ]; then hf_warmup=5; hf_args=(--min-runs 15)
  else                               hf_warmup=2; hf_args=(--min-runs 5 --max-runs 10); fi

  for bench in "${BENCHES[@]}"; do
    [ -n "$ONLY_BENCH" ] && [ "$bench" != "$ONLY_BENCH" ] && continue
    local entry="${ENTRY[$bench]}"
    local args; [ "$regime" = canonical ] && args="${CANON[$bench]}" || args="${HEAVY[$bench]}"

    # The .scm to feed the file-runners (orig for canonical, generated for heavy).
    local scm
    if [ "$regime" = canonical ]; then
      scm="$SCM_DIR/$bench.scm"
    else
      scm="$WORK/heavy-scm/$bench.scm"; mkdir -p "$WORK/heavy-scm"; gen_heavy_scm "$bench" "$scm"
    fi

    echo; echo "==== $bench  (entry=$entry  args='$args'  regime=$regime) ===="

    # Build the candidate runtime list as parallel name/command arrays.
    local names=() cmds=()
    add() { names+=("$1"); cmds+=("$2"); }

    # aot — only if the --multi binary exists.
    local aot_bin="$WORK/$bench/target/release/$entry"
    [ -x "$aot_bin" ] && add aot "$aot_bin $entry $args"

    add jit "$CS --tier vm-jit run $scm"
    add vm  "$CS --tier vm run $scm"
    [ "$regime" = canonical ] && add walker "$CS --tier walker run $scm"

    # rust-O — canonical uses the prebuilt binary; heavy regenerates+compiles.
    local rust_bin
    if [ "$regime" = canonical ]; then
      rust_bin="$RUST_CANON_OUT/$bench"
      if [ ! -x "$rust_bin" ] || [ "$RUST_DIR/$bench.rs" -nt "$rust_bin" ]; then
        mkdir -p "$RUST_CANON_OUT"; rustc -O "$RUST_DIR/$bench.rs" -o "$rust_bin" 2>/dev/null
      fi
    else
      mkdir -p "$RUST_HEAVY_OUT"
      local rust_src="$RUST_HEAVY_OUT/$bench.rs"; rust_bin="$RUST_HEAVY_OUT/$bench"
      subst "$RUST_DIR/$bench.rs" "$rust_src" "${RUST_OLD[$bench]}" "${RUST_NEW[$bench]}"
      if ! grep -qF "${RUST_NEW[$bench]}" "$rust_src"; then
        echo "   !! rust heavy-N substitution failed for $bench (literal not found); skipping rust"
        rust_bin=""
      elif [ ! -x "$rust_bin" ] || [ "$rust_src" -nt "$rust_bin" ]; then
        rustc -O "$rust_src" -o "$rust_bin" 2>/dev/null || rust_bin=""
      fi
    fi
    [ -n "$rust_bin" ] && [ -x "$rust_bin" ] && add rust-O "$rust_bin"

    # External Schemes (skip silently if absent).
    command -v scheme >/dev/null 2>&1 && scheme --help 2>&1 | grep -q -- '--script' && add chez "scheme --script $scm"
    command -v guile  >/dev/null 2>&1 && add guile "guile -q $scm"
    command -v gsi    >/dev/null 2>&1 && add gambit "gsi $scm"
    # Gambit AOT: compile the (regime-specific) .scm to a native .o1, load via gsi.
    if command -v gsc >/dev/null 2>&1 && command -v gsi >/dev/null 2>&1; then
      local gdir="$WORK/gambit-aot/$regime/$bench"; mkdir -p "$gdir"
      # gsc -dynamic versions its output (.o1, .o2, ...) instead of
      # overwriting, so a stale .o1 from a prior N would be loaded.
      # Clean every compiled module first, then load whatever .o* it emits.
      rm -f "$gdir"/m.o* "$gdir/m.scm"
      cp "$scm" "$gdir/m.scm"
      if gsc -dynamic "$gdir/m.scm" >/dev/null 2>&1; then
        local o1; o1=$(ls "$gdir"/m.o* 2>/dev/null | head -1)
        [ -n "$o1" ] && add gambit-aot "gsi $o1"
      fi
    fi

    # Pre-flight: run each once, drop failures, capture the answer for a
    # correctness sanity check. Only survivors go to hyperfine.
    local ref_ans="" ok_names=() ok_cmds=()
    local i
    for i in "${!names[@]}"; do
      local nm="${names[$i]}" cmd="${cmds[$i]}"
      # 120s guard: a badly-chosen heavy N (e.g. a Takeuchi blow-up) must
      # drop the offending runtime, not wedge the whole harness.
      local out; out=$(eval "timeout 120 $cmd" 2>/dev/null); local rc=$?
      if [ $rc -ne 0 ] || [ -z "$out" ]; then
        printf "   %-11s skip (exit %s)\n" "$nm" "$rc"; continue
      fi
      local ans; ans=$(printf '%s\n' "$out" | last_token)
      [ -z "$ref_ans" ] && ref_ans="$ans"
      local mark="ok"; [ "$ans" != "$ref_ans" ] && mark="MISMATCH(got $ans, ref $ref_ans)"
      printf "   %-11s %s  -> %s\n" "$nm" "$ans" "$mark"
      ok_names+=("$nm"); ok_cmds+=("$cmd")
    done
    [ "${#ok_names[@]}" -eq 0 ] && { echo "   (no runnable runtimes)"; continue; }

    # hyperfine over the survivors.
    local hf=(hyperfine -N --warmup "$hf_warmup" "${hf_args[@]}" --style basic
              --export-json "$outdir/$bench.json")
    for i in "${!ok_names[@]}"; do hf+=(-n "${ok_names[$i]}" "${ok_cmds[$i]}"); done
    "${hf[@]}" 2>&1 | grep -E 'Benchmark|mean ±|ran|times faster' | sed 's/^/   /'
  done

  # --- combined markdown table for this regime ---
  python3 - "$outdir" "$regime" <<'PY'
import json, os, sys, math
outdir, regime = sys.argv[1], sys.argv[2]
order = ["aot","jit","vm","walker","rust-O","gambit-aot","chez","guile","gambit"]
benches = ["fib","tak","ack","nqueens","mandelbrot","spectral-norm","binary-trees","alloc-stress"]
data = {}
for b in benches:
    p = os.path.join(outdir, b+".json")
    if not os.path.exists(p): continue
    res = json.load(open(p))["results"]
    data[b] = {r["command"]:(r["mean"],r.get("stddev",0),r["min"]) for r in res}
cols = [c for c in order if any(c in data.get(b,{}) for b in benches)]

def ms(x): return f"{x*1000:.1f}" if x is not None else "—"
lines = []
lines.append("### "+regime+" regime — mean wall time (ms)\n")
lines.append("| bench | " + " | ".join(cols) + " |")
lines.append("|" + "---|"*(len(cols)+1))
for b in benches:
    if b not in data: continue
    row = [b]
    for c in cols:
        v = data[b].get(c)
        row.append(ms(v[0]) if v else "—")
    lines.append("| " + " | ".join(row) + " |")

# relative-to-AOT view (how many x slower than AOT each runtime is)
lines.append("\n### "+regime+" regime — slowdown vs AOT (x; <1 means faster than AOT)\n")
lines.append("| bench | " + " | ".join(cols) + " |")
lines.append("|" + "---|"*(len(cols)+1))
geo = {c:[] for c in cols}
for b in benches:
    if b not in data: continue
    base = data[b].get("aot")
    row = [b]
    for c in cols:
        v = data[b].get(c)
        if v and base and base[0]>0:
            r = v[0]/base[0]; row.append(f"{r:.2f}");
            if c!="aot": geo[c].append(r)
        else:
            row.append("—")
    lines.append("| " + " | ".join(row) + " |")
grow = ["geomean"]
for c in cols:
    xs = geo[c]
    grow.append(f"{math.exp(sum(math.log(x) for x in xs)/len(xs)):.2f}" if xs else "—")
lines.append("| " + " | ".join(grow) + " |")

txt = "\n".join(lines)+"\n"
open(os.path.join(outdir, "..", regime+"-table.md"),"w").write(txt)
print("\n"+txt)
PY
}

case "$REGIME" in
  canonical) run_regime canonical ;;
  heavy)     run_regime heavy ;;
  both)      run_regime canonical; run_regime heavy ;;
  *) echo "bad --regime: $REGIME"; exit 2 ;;
esac

echo "==> JSON + markdown tables under $WORK/results/"
